### ISSUE TITLE
Sub-Task: Fullscreen

### ISSUE THREAD

**Issue by Fizzy78** [kidnamedfinger1/keymaster#52]

**Comment by Emi-4** [comment]
fullscreen toggle is partially functional. it does fullscreen the game, but it doesnt resize anything so all the elements of the game huddle up in a corner. #42

**Comment by Fizzy78** [comment]
Incomplete due to absence. Will complete next week.

**Comment by Emi-4** [comment]
super close to finished. resizes most everything, just a few things remaining to resize and move around and it will be done!

**Comment by Fizzy78** [comment]
THIS WAS BUILT IN ALL ALONG.

**Comment by Fizzy78** [comment]
Fix the infinite debug.
