### ISSUE TITLE
Sub-Task: Keymonkey Sniper

### ISSUE THREAD

**Issue by Fizzy78** [kidnamedfinger1/keymaster#61]
Extremely slow Keymonkey but it is always accurate.
Sub-Task of: #59

**Comment by OmarH07** [comment]
Delayed. It will be finished on Sprint 10, but I might take some time.

**Comment by OmarH07** [comment]
Done. The Keymonkey Sniper will take longer than a Keymonkey Grunt, but it will always guess correctly.
